---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookie
  labels:
    app: bot
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: slack-twitter-bot-cookie
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slack-twitter-bot-cookie
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: twi-slack-bot
    name: cookie
  nfs:
    server: nfs.unipro.infra
    path: /nfs/users/yuito-it/slackTwitter/cookie
