---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: mysql
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: slack-twitter-bot-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slack-twitter-bot-db
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: slack-twitter-bot
    name: db
  nfs:
    server: nfs.unipro.infra
    path: /nfs/users/yuito-it/slackTwitter/db
